AllCops:
  TargetRubyVersion: 2.3

LineLength:
  Max: 150

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/VariableNumber:
  Enabled: false

ParameterLists:
  Max: 10
  CountKeywordArgs: false

